### PR TITLE
Drag and Drop sorting for Vidi.

### PR DESCRIPTION
**Pull request by jmverges**
Drag and drop for Vidi. 
I found some problems with Javascript in CMS 7.0.3 because of drag and drop into a iframe. I need to test it in other versions. Please, take a look if you can.
I don't know if moveAction was thought to sort records and I didn't see where is used moveAction so, I created other one.
The code could be better.

### CODE REVIEW

**Comment by fabarea** [comment]
Let me work on this patch again... Are you still around / alive?

**Comment by jmverges** [comment]
Sure, I'm here

**Comment by fabarea** [comment]
I have reworked your code which was a great start. Now, I have one problematic to solve. What happen is the User has already sorted its list by another criteria, like A-Z, should we disable drag & drop in this case? Because it does not make sense to sort manually if we have an alphabetic sorting active...

**Comment by jmverges** [comment]
You are right, I had same thought. However I just disabled sorting. I think we could disable drag & drop on any kind of sorting different to default sorting and ext:vidi should use by default the original sorting if developer doesn't change it, do you agree?

**Comment by fabarea** [comment]
Yeah, make sense, I polished the implementation by removing the sort icon from the top header. I put the patch on [this branch](https://github.com/fabarea/vidi/tree/feature/sorting) ready for comment.

**Comment by fabarea** [comment]
Thanks for your work... even if I was slow integrating it! What URL (twitter, blog?) do you want me to link for your credits. Releasing Vidi 1.1.0 right now...

**Comment by jmverges** [comment]
No problem, just github profile if you like :+1:

**Pull request closed without merging**
