### PR TITLE
[FEATURE] Make Row View class configurable

### PR DESCRIPTION
**Pull request by mostwanted1976**

### CODE REVIEW

**Comment by mostwanted1976** [comment]
This pull request is based on https://review.typo3.org/#/c/35785/ but uses the updated namespace EXT:vidi uses.

**Comment by fabarea** [comment]
Just to make sure why can't we XCLASS here as described [here](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Xclasses/Index.html)? I have the impression we implement what the object manager is already capable - which looks wrong IMO.

**Comment by mostwanted1976** [comment]
I guess you are right: it does not make much sense to reinvent this feature in EXT:vidi. In a current project XClass-ing the `Fab\Vidi\View\Grid\Row` worked like a charm.

**Comment by fabarea** [comment]
ok, fine like that.

**Comment by mostwanted1976** [comment]
I guess the possibility to configure the `Row` view class would be advantageous compared to XClass-ing `Fab\Vidi\View\Grid\Row`:

Former would be a feature of EXT:vidi and thus part of it's public API. The latter is only a feature of TYPO3 and will not guarantee you that the XClassed `Fab\Vidi\View\Grid\Row` will still exist in upcomming versions of EXT:vidi. So every update of EXT:vidi could potentially break a project.

What do you think about it?

**Pull request closed without merging**
